version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - "5672:5672"   # RabbitMQ service port
      - "15672:15672" # RabbitMQ management interface port

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: ameda
      POSTGRES_PASSWORD: rootUser@123
      POSTGRES_DB: rabbit
    ports:
      - "5432:5432" # PostgreSQL service port

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "80:80" # pgAdmin service port
    depends_on:
      - postgres
