spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/rabbit
    username: ameda
    password: rootUser@123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    addresses: localhost:5672
server:
  port: 9097